# Generated by Django 5.2.7 on 2025-10-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_path',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
